import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MailModal from "@/components/mail/MailModal";
import { Suspense } from "react";
import ToastifyContainer from "@/components/providers/ToastifyContainer";
import LoadingPage from "@/components/Loading";


export const metadata: Metadata = {
  title: "mo3ito resume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" h-max w-full bg-slate-200 dark:bg-black overflow-y-scroll">
        {children}
        <Suspense fallback={<LoadingPage/>}>
        <MailModal/>
        </Suspense>
        <ToastifyContainer/>
        </body>
    </html>
  );
}
