import type { Metadata } from "next";
import { Inter , Syne , Tilt_Neon} from "next/font/google";
import "./globals.css";
import MailModal from "@/components/mail/MailModal";
import { Suspense } from "react";
import ToastifyContainer from "@/components/providers/ToastifyContainer";
import LoadingPage from "@/components/Loading";

const tiltNeon = Tilt_Neon({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-tiltNeon',
})

const syne = Syne({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-syne',
})
 

export const metadata: Metadata = {
  title: "mo3ito resume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${syne.variable} ${tiltNeon.variable} h-max w-full bg-slate-200 dark:bg-black overflow-y-scroll text-zinc-600 dark:text-zinc-300`}>
        {children}
        <Suspense fallback={<LoadingPage/>}>
        <MailModal/>
        </Suspense>
        <ToastifyContainer/>
        </body>
    </html>
  );
}
