import type { Metadata } from "next";
import {  Josefin_Sans , Exo_2} from "next/font/google";
import "./globals.css";
import MailModal from "@/components/mail/MailModal";
import { Suspense } from "react";
import ToastifyContainer from "@/components/providers/ToastifyContainer";
import LoadingPage from "@/components/Loading";

const exo2 = Exo_2({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-exo2',
})

const josefinsSans = Josefin_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-josefinsSans',
})
 

export const metadata: Metadata = {
  title: "mo3ito resume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={` ${josefinsSans.variable} ${exo2.variable} font-josefinsSans h-max w-full bg-slate-200 dark:bg-black overflow-y-scroll text-zinc-600 dark:text-zinc-300`}>
        {children}
        <Suspense fallback={<LoadingPage/>}>
        <MailModal/>
        </Suspense>
        <ToastifyContainer/>
        </body>
    </html>
  );
}
