import Navbar from "@/components/Navbar";
import AsideLeft from "@/components/AsideLeft";

export default function Home() {
  return (
    <main className="w-full mx-auto flex  p-14 relative ">
      <AsideLeft />
      <Navbar />
      <p className="w-8/12 absolute right-20 h-full pl-4 dark:text-pink-200 text-violet-600 pt-96">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Expedita officiis corporis voluptatibus itaque, minus quam debitis. Suscipit, rem rerum voluptate quas ipsam cum ipsa laudantium doloribus. Assumenda vitae veniam velit.
      Tempore, libero nihil. Excepturi eum quas temporibus odit. Quis excepturi libero veritatis esse laborum velit illo minima eaque cum quibusdam ipsum earum fugiat temporibus, labore ad, placeat, debitis deserunt accusamus!
      Sunt aliquam modi nam adipisci mollitia fugiat exercitationem eligendi, in facere perspiciatis distinctio ad deserunt aspernatur eum accusamus recusandae, sapiente accusantium earum dicta doloribus eaque. Placeat quaerat quasi sunt voluptatem.
      Vitae tenetur voluptatibus, laboriosam fuga reiciendis facilis sunt ipsa neque quam quia officiis illo quod nostrum. Nobis facere vero enim expedita, aliquam, pariatur aut exercitationem temporibus officiis deleniti voluptatibus vel!
      Ducimus aspernatur nemo, quisquam, enim velit error dolorum cupiditate eaque facilis sed totam perspiciatis architecto alias porro dignissimos omnis, cum quis vitae dolores molestiae distinctio ut amet. Est, voluptatum corporis?
      Corrupti rerum, nulla commodi doloremque voluptatem aspernatur inventore quasi, repellendus incidunt odio quo vitae asperiores laborum nisi deleniti error expedita, rem ab cupiditate sequi soluta harum earum. Debitis, culpa dignissimos?
      Quibusdam nemo accusamus eaque laudantium autem eligendi quis dolores quo minus repellat, quos, ea nobis corporis esse qui rerum labore harum fuga quia dolorem, reprehenderit consectetur repellendus voluptatem. Debitis, necessitatibus.
      Quisquam eveniet perspiciatis, recusandae, inventore dolor ad aperiam quidem animi deleniti pariatur, nihil dolorem? Quibusdam facilis, animi eligendi perferendis, veniam autem eius dolor ipsum culpa nesciunt in sunt consequuntur officiis.
      Hic, aliquam natus non fugiat labore quibusdam laborum corporis saepe optio quidem tempora dolorem incidunt dolorum rerum expedita perferendis unde est provident vero maxime. Ipsam at veritatis sequi beatae facere?
      Dignissimos magnam ea similique reprehenderit atque aperiam blanditiis vel asperiores dolor distinctio quod enim maxime earum, molestiae delectus. Molestiae non mollitia et possimus ratione, iure soluta totam sed facere quidem.
      Quidem tempore veniam deserunt nesciunt dolores. Labore quia, aut expedita beatae magnam repudiandae eos quidem, aperiam provident distinctio eligendi perspiciatis exercitationem id! Illum doloremque nobis minima ullam cupiditate temporibus suscipit.
      Qui quibusdam blanditiis nemo, ducimus neque, obcaecati mollitia quisquam temporibus sequi corporis doloribus fuga laudantium maxime fugit officia tempore iusto cumque. Iusto quaerat quia doloremque temporibus facilis, saepe libero itaque?
      Autem doloremque in maiores neque non! Ipsam, blanditiis illum optio laboriosam a voluptate necessitatibus! Consequatur quo ipsam rerum quos officia a ut vel illo porro, nemo, earum, quidem voluptates impedit?
      Nisi vero perspiciatis, illum placeat iure eveniet incidunt aliquam sapiente magni deleniti animi. Repudiandae, neque? Ex expedita harum ut. Ab commodi magni asperiores reprehenderit tempore in placeat doloremque, dicta fugit!
      Illo, natus? Accusamus odit iure quis dolore non repellat voluptates nam? Voluptates sint odit, voluptate non repellendus nihil reiciendis dolor! At voluptates ad eligendi tenetur non, doloribus possimus! Eum, recusandae!
      Quasi sed nobis vel voluptatibus repudiandae, sint dolore nesciunt ut cumque velit amet harum at perspiciatis ullam totam earum commodi voluptatum obcaecati delectus, ducimus molestias laboriosam recusandae qui? Laboriosam, atque.
      Voluptatibus temporibus repudiandae consectetur! Expedita suscipit ullam ad id hic, porro neque saepe officiis odio ex illo doloremque possimus? Reiciendis laboriosam, consequatur quo non debitis sunt. A neque provident saepe.
      Est eos incidunt unde, fuga magnam voluptas libero error reiciendis hic quisquam mollitia nostrum quos illo consequatur itaque corrupti, molestias dicta soluta fugit expedita? Unde esse voluptas possimus asperiores dolore?
      Ad enim, eum quae inventore ratione dolorem dignissimos ipsa repellat, consequatur iure expedita earum culpa voluptates unde obcaecati eligendi hic quasi tenetur quia vel. Ut nihil repellendus soluta minima dicta.
      Eligendi, sint, tenetur vero voluptatem praesentium omnis ea molestias illo ipsa molestiae iste, facilis nulla culpa rerum! Tempore consectetur architecto, assumenda rerum aut numquam, excepturi, repudiandae maxime vitae accusamus hic!
      Delectus molestiae ducimus magni consequatur velit provident explicabo amet reiciendis voluptatum labore deserunt dolorum nam natus dolore odit repellendus facere, in aperiam dolorem dolores ut libero eligendi doloremque? Pariatur, beatae.
      Vero, eum harum. Quia ab perspiciatis eius quas nobis amet iusto nihil exercitationem nam, enim molestias rerum dolorem in temporibus natus totam id illum reprehenderit quis facere. Similique, enim veniam?
      Aliquid aliquam provident atque dolores minima ut recusandae aspernatur est nihil deserunt quisquam consequatur, molestias nam, commodi sequi illo nesciunt quaerat labore, rerum inventore magnam amet! Ipsam rem unde adipisci.
      Beatae quam facilis, et dolores hic laboriosam cumque voluptatum corporis dolor amet in sed unde quia accusantium adipisci expedita perferendis suscipit dolorum molestias dolorem nihil quidem distinctio? Molestias, provident a.
      Velit, accusamus optio sequi eum tempore repellendus, blanditiis perspiciatis odit quo aliquam magni nobis fuga expedita repudiandae excepturi eius similique cum aliquid. Iste pariatur, nisi modi quos aut repudiandae tenetur.
      Tempore accusamus earum hic! Quo sit autem qui culpa dignissimos id reprehenderit aut vero ex corporis, sunt nobis rem neque itaque ad aperiam! Ullam quas obcaecati unde quaerat consectetur debitis.
      Voluptates natus corrupti officia vel, laboriosam libero soluta eos odit vitae in provident cum obcaecati reprehenderit animi architecto quaerat molestiae quam. Eaque facilis omnis temporibus illum provident ut officia expedita!
      Quam consequatur, aliquid sapiente optio labore commodi inventore fugiat, saepe magnam quidem vitae delectus dolore eos ducimus accusantium, sequi sint nemo! Illum accusamus expedita ab non saepe modi. Voluptate, modi.
      Repellat laudantium ipsa quasi in? Suscipit exercitationem distinctio quis temporibus ducimus velit maiores fuga possimus dolorem hic, eligendi veniam excepturi tempora maxime cumque beatae quae! Maiores molestias esse soluta rem?
      Blanditiis error, veritatis corporis fuga inventore omnis alias. Consectetur blanditiis provident aliquid dolores consequuntur non minima culpa! Molestiae nam rerum praesentium voluptatum voluptatem, iste commodi, accusamus minima suscipit nulla quaerat.
      Repudiandae autem exercitationem itaque delectus, cumque quidem mollitia placeat accusantium quas natus molestiae illum rem voluptates quod ipsum officiis, magnam temporibus? Reiciendis voluptatem eligendi consectetur necessitatibus possimus molestias corrupti debitis.
      Incidunt, beatae aspernatur. At, maxime a placeat voluptas magnam assumenda, eligendi non explicabo itaque ea modi nam libero aliquid. Excepturi blanditiis facere aliquid tempore quasi tempora explicabo nulla! Eveniet, soluta!
      Modi, molestiae porro! Architecto sed incidunt earum porro saepe! Quidem, ab. Deserunt alias voluptatum minus dignissimos beatae ipsa, aspernatur dolores quod atque molestias cupiditate vero dolor modi, et asperiores facere.
      Libero expedita voluptatibus sint obcaecati neque eligendi atque, omnis provident iure, consectetur nesciunt delectus cum saepe placeat! Maxime fuga, soluta, accusamus quis vitae unde nesciunt ipsa placeat et consequuntur rerum.
      Eos voluptatum, enim, fugiat omnis maxime ea eveniet aliquam doloremque necessitatibus repudiandae in assumenda dicta dolores error recusandae praesentium velit animi voluptate expedita deserunt. Sapiente dignissimos provident blanditiis velit accusamus?
      Labore consequuntur fugit nemo vitae error! Voluptates, vero architecto! Alias voluptatem assumenda iste! Sequi facere fugiat dignissimos temporibus ea error, molestias omnis itaque assumenda non earum tempore quia repellat praesentium.
      Dignissimos quisquam libero mollitia aut id saepe, esse rerum veniam placeat quidem enim accusantium explicabo excepturi eos ratione assumenda earum culpa! Voluptatibus nemo dignissimos aperiam magnam tempora, illo error impedit!
      Voluptatum, assumenda ratione. Recusandae excepturi adipisci dolore reiciendis inventore minima dicta ipsum laudantium, odio est iusto odit at dolor vero consectetur ad dolores unde nobis. Dolorem similique ea repudiandae voluptas?
      Iure aliquid debitis atque ipsa, minima ad facilis eaque? Omnis facere iste architecto tenetur deserunt. Quasi quaerat beatae, pariatur et animi laborum debitis voluptate magnam blanditiis ea doloribus adipisci amet?
      Possimus similique, tempora aliquam corrupti beatae eos molestias officiis, quis aspernatur ad itaque nihil illo, facere consectetur! Optio vitae suscipit minus atque quaerat obcaecati inventore eos, nemo tempore earum facilis?
      Asperiores animi temporibus, voluptate quis, soluta dolorum natus molestiae fugiat autem ratione magni repellat esse! Esse mollitia natus molestiae totam, voluptatum quos nemo tempora repudiandae deleniti, hic, autem asperiores nesciunt.
      Accusamus rem ex perferendis, ipsam quisquam libero adipisci consequuntur perspiciatis excepturi quaerat facere est iure, dicta impedit maiores consectetur omnis quibusdam recusandae quidem consequatur a hic quam voluptatem! Sint, eum.
      Magnam ipsa natus id, deleniti provident et nisi nemo totam nam nulla quasi dolorum, voluptatum qui voluptas asperiores molestiae itaque. Deserunt tempore accusamus fugiat dolorem quo. Labore doloribus hic commodi?
      Fugiat blanditiis quia facere mollitia excepturi dolore? Nostrum error vero cum voluptate, repudiandae facilis saepe, ex iure eos optio provident enim minima ipsa, inventore labore. Possimus deserunt qui ab! Saepe.
      Commodi, vero unde praesentium vel possimus iusto dicta quod tempora dignissimos. In quos debitis repudiandae, inventore quod voluptates dolore tempore saepe ullam cupiditate explicabo quo fugiat hic odio nisi quia!
      Rem, quos quae reiciendis quisquam ab, veritatis illum iure tenetur eligendi molestias saepe nam? Blanditiis nam laudantium tempora veritatis facere, suscipit aliquid, doloribus alias delectus quam voluptates fuga consectetur reiciendis.
      Quasi nobis cupiditate hic tenetur, sint rem possimus eos, labore sit ratione explicabo suscipit. Atque harum quidem sed et sequi quod enim! Cupiditate quas sed, et repellendus voluptate facilis veritatis!
      Accusantium illo error earum, rem quia veritatis. Ut dolore voluptas ullam, accusamus assumenda consectetur, officiis neque facere soluta minima velit odit, sint eligendi vero cumque repudiandae praesentium nisi voluptate ducimus!
      Reprehenderit suscipit enim commodi placeat aperiam, vel ullam saepe. Facilis in exercitationem esse quis animi vero, corrupti reprehenderit possimus similique porro ducimus molestiae commodi deleniti libero quos doloribus aliquid culpa?
      Itaque soluta exercitationem, numquam reiciendis aut sed nulla voluptatibus quia esse iste aliquid corporis pariatur porro suscipit a non? Fugiat quos deleniti eaque consequuntur dolore at magni, esse voluptate laudantium!
      Laudantium consequuntur aliquid molestiae sunt possimus est iste, quod dolore soluta necessitatibus quaerat deleniti maxime voluptatum dicta. Incidunt, voluptatem voluptate assumenda dignissimos est atque neque, maxime impedit, numquam recusandae reprehenderit.
      Aspernatur quod, non accusamus deleniti tenetur porro vitae nihil laudantium voluptate mollitia cum aliquid quam fugiat quas iure inventore ullam saepe ab recusandae asperiores, nisi doloribus. Accusantium assumenda optio atque.
      Voluptatibus maiores illum atque nobis quis ea adipisci consectetur, voluptatem laborum esse, ratione inventore veniam, sint consequuntur aut consequatur amet neque odio necessitatibus debitis alias minima. Rem minima deserunt ducimus.
      Molestias cumque adipisci optio magnam quaerat. Earum quod maiores nemo quam repellat accusamus veritatis laboriosam consequatur dolores! Reiciendis, quisquam veritatis magni earum voluptatem maiores numquam dolorem harum aperiam natus atque.
      Nisi sed odit quod voluptas aperiam a fuga, quis, numquam doloremque esse ipsam minus harum, sapiente dolores eligendi? Amet consequatur aspernatur veniam voluptate vitae ducimus obcaecati dolorem exercitationem itaque enim.
      Velit facilis atque nesciunt distinctio alias eaque veniam praesentium minus, neque ipsam quis sit expedita rerum minima nam explicabo eligendi necessitatibus, quia est itaque! Quos reiciendis molestias odit distinctio nisi!
      Autem assumenda veritatis iure quidem, voluptates nisi unde. Ipsa velit repellendus praesentium, quisquam itaque cupiditate reprehenderit? Itaque, quia adipisci rerum aperiam blanditiis iure ipsum illum rem nesciunt repellendus dolor architecto.
      Soluta, quis eaque saepe animi impedit magnam earum iste iusto, pariatur nostrum non quam minus blanditiis excepturi libero, facere sapiente possimus molestiae itaque nesciunt delectus at! Explicabo accusamus ex temporibus?
      Sit laudantium quaerat ducimus modi, minus quia sed error, quam fuga facilis placeat exercitationem, aspernatur quis rem aliquid impedit soluta? Provident recusandae hic molestias temporibus dolores obcaecati nisi. Voluptatum, facere?
      Porro praesentium accusantium, cumque omnis dolorum veniam dignissimos ut dolorem architecto laborum facere, voluptatibus maiores suscipit necessitatibus nisi itaque! Corporis error ut fuga. Ea sint exercitationem quo, quae vero dicta?
      Quaerat pariatur eaque provident hic atque dolorem incidunt quam ab? Pariatur a omnis autem, necessitatibus excepturi velit consequatur quae aspernatur, doloremque ad quos voluptatibus voluptatem voluptate in, hic dicta adipisci.
      Adipisci expedita possimus delectus incidunt deleniti. Sunt impedit voluptas voluptatum architecto exercitationem odit in accusamus, illo praesentium id soluta dolores officia dolor excepturi laudantium laborum. Culpa deleniti laudantium fuga sed.
      Ea fugit ducimus modi distinctio quisquam veniam praesentium nostrum exercitationem ex recusandae assumenda, vitae sunt dolorum at itaque? Ipsum sed natus atque, doloremque excepturi ab numquam at nam inventore minima.
      Ut enim, nihil sunt facere expedita vero rerum possimus pariatur, dolorum esse porro unde doloremque dolorem sit eveniet, quaerat laboriosam quasi a? Explicabo asperiores nam, eum pariatur obcaecati ipsam iste?
      Officiis perferendis obcaecati velit sequi, qui expedita ducimus? Fuga exercitationem similique quidem consequuntur voluptate placeat dolorum veniam nemo provident eius quam pariatur alias, ut non possimus voluptas totam. Illum, reprehenderit?
      Fugiat corrupti excepturi vero sint quam debitis unde accusantium ut suscipit atque necessitatibus, soluta voluptates, recusandae error autem quas nisi consequuntur. Earum velit ad explicabo magni, inventore doloremque quia tempora?
      Nemo veritatis omnis itaque autem sapiente iure maiores. Explicabo, quis a dolores, ratione temporibus porro laborum officia fuga debitis eius eligendi culpa recusandae quod voluptatum. Dolorem placeat aut porro aliquid?
      Quibusdam maxime labore sint voluptate odit quod laborum officiis quia vitae omnis facilis magnam doloremque similique, repellat fugiat, quaerat enim totam voluptatem? Repellendus nostrum neque inventore quam recusandae iure repudiandae?
      Nihil, libero? Quisquam ipsum maiores repellat officiis iusto ex molestiae nesciunt quas maxime assumenda eum cupiditate qui ducimus id, ipsa minus soluta. Soluta consequuntur suscipit odio molestiae culpa accusantium eos.
      Consectetur sit totam debitis, consequuntur, labore fugit in reiciendis nihil provident maiores, aliquid accusamus doloremque saepe molestiae enim qui. Tenetur suscipit at maxime incidunt perspiciatis obcaecati eveniet asperiores quidem laborum.
      Veritatis, aliquam sapiente molestias tenetur accusamus accusantium alias aspernatur id non quisquam nemo quam dolore voluptates facere explicabo, libero similique. Maiores debitis aliquid molestias facere modi delectus commodi soluta ad!
      Fugit facere rerum at minima. At asperiores nobis eum voluptates fuga assumenda ullam magnam ea totam! Distinctio sunt nulla cum totam aliquid! Laboriosam accusamus quos, perspiciatis inventore eum impedit blanditiis.
      Ad iste voluptatum, commodi accusamus labore tempora excepturi veniam dolorem incidunt magni qui consequuntur tempore cumque minus deserunt necessitatibus vel inventore laboriosam perferendis unde nesciunt id hic! Natus, sapiente veniam.
      Sit, doloribus et veniam blanditiis culpa incidunt aut amet itaque ex cumque soluta cum eos autem, reprehenderit voluptatibus enim explicabo maiores fugit totam impedit quasi dolor. Numquam pariatur necessitatibus dolorum!
      Alias cum, quo, possimus magni pariatur sed consequatur officia, veniam illo deserunt laboriosam? Blanditiis, accusantium quibusdam ad magni ea vel ut necessitatibus voluptas! Rerum eius id provident, ut ex itaque!
      Saepe, culpa eveniet fugit nulla possimus laborum libero, iure hic ea maiores fugiat delectus eligendi asperiores quas adipisci. Quis accusantium delectus modi eum, eius molestiae expedita recusandae quia necessitatibus rem!
      Nam blanditiis amet, voluptas quas nesciunt dolor fugit aperiam doloribus ducimus culpa quidem est odio vitae sequi quibusdam, maxime, dolore quia nostrum! Nihil repellat expedita dignissimos repellendus quidem dolores non.
      Itaque rerum, reiciendis dolorum, consectetur est, vero dicta dolore laborum nobis veritatis repellat fugit optio. Ex, laudantium qui. Esse incidunt asperiores in? Ducimus id ad, autem labore necessitatibus numquam obcaecati.
      Dolore minus voluptates, ipsum, quia sint harum aperiam voluptatem corrupti ipsa veritatis repudiandae quam id excepturi, quod illum facilis a dolor mollitia culpa autem vel atque esse ea? Modi, dicta.
      Incidunt commodi nihil explicabo praesentium, modi ratione facere provident natus ducimus numquam repudiandae error nostrum pariatur nam. Velit impedit libero deleniti fuga vel? Fuga quis impedit numquam praesentium enim molestiae!
      Obcaecati cum necessitatibus repellat voluptas libero inventore dolorum provident possimus. Optio, ipsam id magnam voluptatibus tenetur quaerat fuga libero? Ducimus repudiandae, qui veniam autem aliquam aperiam consectetur cupiditate tenetur. Eos.
      Eos, dolor esse! Aperiam, quos expedita velit placeat vero, mollitia doloremque molestias ipsam, iure dolores sint assumenda! Nulla ipsa doloribus, beatae rem nisi odio nihil vitae repellat esse ea architecto.
      Sequi, alias quae rem aliquam error aspernatur quisquam illo voluptatem repellendus dolor corporis tempora sapiente fugiat tempore quam totam. Quo harum blanditiis voluptatibus sit! Rerum incidunt rem quia corporis magnam.
      Dolore temporibus veritatis consequuntur, recusandae, officiis, ipsam doloremque quod sunt eos sapiente quos cupiditate eveniet laboriosam amet modi molestias ex consequatur eius placeat quia? Dolorum nobis quae ab perspiciatis reprehenderit.
      Perspiciatis omnis odit illum, mollitia debitis optio ut iusto similique temporibus fugiat illo doloribus earum quos eius, dolor natus quibusdam harum. Necessitatibus fugiat neque tempora distinctio nemo eligendi impedit quaerat.
      Vitae pariatur rerum, sed facilis doloribus deleniti temporibus aliquam rem blanditiis eum ad corrupti delectus in dicta consequuntur suscipit, amet unde? Ducimus, laudantium deserunt hic sit eaque placeat ullam harum.
      Deserunt, animi tempora sequi corrupti alias libero saepe molestias qui neque soluta rem vero beatae doloremque perferendis ut porro, asperiores laudantium, iure temporibus ex numquam? Minus aperiam deserunt laudantium quasi?
      Recusandae nulla voluptate obcaecati ratione ipsam molestiae voluptatum facere ea ullam blanditiis enim quidem reprehenderit laboriosam adipisci iusto ab, aliquid fugit saepe quis voluptas? Deleniti expedita veniam dolores quos excepturi!
      Labore hic consequatur dignissimos ipsa ex sint alias obcaecati eligendi neque dolorem nam, nobis expedita debitis assumenda itaque laboriosam quisquam, voluptas quis? Repudiandae hic perferendis saepe quam nisi optio ad?
      Quasi obcaecati quo rem fuga suscipit ad inventore voluptate voluptatibus aliquid assumenda, sapiente, incidunt velit doloribus vero? Architecto alias fugiat nisi quo voluptate, minus labore exercitationem itaque vitae quidem mollitia.</p>
    </main>
  );
}
